spring:
  application:
    name: calendar-back
  datasource:
    url: jdbc:mariadb://localhost:3306/planup
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
springdoc:
  use-management-port: false
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v1/api-docs
  override-with-generic-response: false